### ISSUE TITLE
imcontactlist not in WellKnownFolderName enumeration

### ISSUE THREAD

**Issue by rich-perry** [OfficeDev/ews-managed-api#10]
When calling SyncFolderHierarchy with the WellKnowFolderName property in the property set the request fails as the imcontactlist is not in the WellKnowFolderName enumeration.

**Comment by dclaux** [comment]
IMContactList is coming, thanks for reporting this. Your change will be part of the updated source code that is coming shortly.
As for WorkingSet, it doesn't appear to be in the EWS schema, so it won't be in the API.
