### ISSUE TITLE
"Internal Server Error" thrown by EnableAlwaysCategorizeItemsInConversations()

### ISSUE THREAD

**Issue by avereshchak** [OfficeDev/ews-managed-api#162]
One of our clients who is using our product has started experiencing a strange "Internal Server Error" thrown by ExchangeService.EnableAlwaysCategorizeItemsInConversations() which worked for him before.

I do not have access to his mailbox (it's an Office365 account) and have only the EWS logs (please find them [attached](https://github.com/OfficeDev/ews-managed-api/files/1789445/ews_logs.txt)). Unfortunately it wasn't a transient error and I had to disable the autocategorization feature in our product to allow him using other features.

What could cause that problem? Has anyone experienced it or has ideas on how to troubleshoot it?

Thanks,
Anton

**Comment by avereshchak** [comment]
The things getting worse. Now my corporate O365 account is affected by "Internal Server Error" Exchange error identical to the one attached in my original post. Any ideas guys?

Here is a sample code which throws a ServiceResponseException:

    var propertySet = new PropertySet(
        BasePropertySet.IdOnly, 
        ItemSchema.ConversationId);

    var emails = service.FindItems(
        WellKnownFolderName.Inbox, 
        new ItemView(100)
        {
            PropertySet = propertySet
        });

    var ids = emails.Select(i => i.ConversationId)
                    .Distinct()
                    .Take(10)
                    .ToList();

    var categories = new[] {"My category"};
    var response = service.EnableAlwaysCategorizeItemsInConversations(
        ids, 
        categories, 
        true);

**Comment by avereshchak** [comment]
Seems it's fixed now, my sample and product are working fine.

Does Microsoft informs about any updates being made to O365 servers? It'd be useful to monitor for breaking changes.

Thanks!

**Comment by davster** [comment]
For bug fix level stuff, not that I am aware of.  For larger scale stuff, there will typically be blog posts or other public announcements.
