### ISSUE TITLE
MeetingRequest does not have a public constructor

### ISSUE THREAD

**Issue by 4alexey** [OfficeDev/ews-managed-api#17]
MeetingRequest class does not have public constructor. The only way to create a MeetingReques is by creating associated Appointment and calling it's CreateAcceptMessage or CreateDeclineMessage.

This is not sufficient for the the scenario when the Appointment had been cancelled. Corresponding MeetingRequest(s) IsAssociated property is null, and AssociatedAppointmentId is null therefore. There is no easy way to create these MeetingRequests for the purpose of migration, for example.

Proposal: Change internal constructor to public, as below. Created MeetingRequest can be then passed to CreateItems API and created on the ExchangeServer.

public MeetingRequest(ExchangeService service)
    : base(service)
{
}

**Comment by dclaux** [comment]
This is by design. Meeting requests are created by Exchange as a result of creating a meeting and adding attendees.

**Comment by Sodininkas** [comment]
Why this is closed, this feature is - Must be added
