### ISSUE TITLE
MissingManifestResourceException in ExchangeResourceManager

### ISSUE THREAD

**Issue by 4alexey** [OfficeDev/ews-managed-api#18]
{Name = "MissingManifestResourceException" FullName = "System.Resources.MissingManifestResourceException"}
    [System.RuntimeType]: {Name = "MissingManifestResourceException" FullName = "System.Resources.MissingManifestResourceException"}
    base: {Name = "MissingManifestResourceException" FullName = "System.Resources.MissingManifestResourceException"}
    Assembly: {mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089}
    AssemblyQualifiedName: "System.Resources.MissingManifestResourceException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"
    Attributes: Public | Serializable | BeforeFieldInit
    BaseType: {Name = "SystemException" FullName = "System.SystemException"}
    ContainsGenericParameters: false
    DeclaringMethod: 'ex.GetType().DeclaringMethod' threw an exception of type 'System.InvalidOperationException'
    DeclaringType: null
    FullName: "System.Resources.MissingManifestResourceException"
    GenericParameterAttributes: 'ex.GetType().GenericParameterAttributes' threw an exception of type 'System.InvalidOperationException'
    GenericParameterPosition: 'ex.GetType().GenericParameterPosition' threw an exception of type 'System.InvalidOperationException'
    GenericTypeArguments: {System.Type[0x00000000]}
    GUID: {726bbdf4-6c6d-30f4-b3a0-f14d6aec08c7}
    HasElementType: false
    IsAbstract: false
    IsAnsiClass: true
    IsArray: false
    IsAutoClass: false
    IsAutoLayout: true
    IsByRef: false
    IsClass: true
    IsCOMObject: false
    IsConstructedGenericType: false
    IsContextful: false
    IsEnum: false
    IsExplicitLayout: false
    IsGenericParameter: false
    IsGenericType: false
    IsGenericTypeDefinition: false
    IsImport: false
    IsInterface: false
    IsLayoutSequential: false
    IsMarshalByRef: false
    IsNested: false
    IsNestedAssembly: false
    IsNestedFamANDAssem: false
    IsNestedFamily: false
    IsNestedFamORAssem: false
    IsNestedPrivate: false
    IsNestedPublic: false
    IsNotPublic: false
    IsPointer: false
    IsPrimitive: false
    IsPublic: true
    IsSealed: false
    IsSecurityCritical: false
    IsSecuritySafeCritical: false
    IsSecurityTransparent: true
    IsSerializable: true
    IsSpecialName: false
    IsUnicodeClass: false
    IsValueType: false
    IsVisible: true
    MemberType: TypeInfo
    Module: {CommonLanguageRuntimeLibrary}
    Namespace: "System.Resources"
    ReflectedType: null
    StructLayoutAttribute: {System.Runtime.InteropServices.StructLayoutAttribute}
    TypeHandle: {System.RuntimeTypeHandle}
    TypeInitializer: null
    UnderlyingSystemType: {Name = "MissingManifestResourceException" FullName = "System.Resources.MissingManifestResourceException"}

Call Stack:
>	Microsoft.Exchange.WebServices.Data.dll!Microsoft.Exchange.WebServices.Data.ExchangeResourceManager.GetString(string name, System.Globalization.CultureInfo culture) Line 121	C#
 	Microsoft.Exchange.WebServices.Data.dll!Microsoft.Exchange.WebServices.Data.LocalizedString.System.IFormattable.ToString(string format, System.IFormatProvider formatProvider) Line 435	C#
 	Microsoft.Exchange.WebServices.Data.dll!Microsoft.Exchange.WebServices.Data.LocalizedString.ToString() Line 382	C#
 	Microsoft.Exchange.WebServices.Data.dll!Microsoft.Exchange.WebServices.Data.LocalizedString.implicit operator string(Microsoft.Exchange.WebServices.Data.LocalizedString value) Line 135	C#
 	Microsoft.Exchange.WebServices.Data.dll!Microsoft.Exchange.WebServices.Data.PropertyBag.this[Microsoft.Exchange.WebServices.Data.PropertyDefinition].set(Microsoft.Exchange.WebServices.Data.PropertyDefinition propertyDefinition, object value) Line 375	C#
 	Microsoft.Exchange.WebServices.Data.dll!Microsoft.Exchange.WebServices.Data.Item.ArchiveTag.set(Microsoft.Exchange.WebServices.Data.ArchiveTag value) Line 951	C#

**Comment by dclaux** [comment]
This issue has been resolved with this commit: https://github.com/OfficeDev/ews-managed-api/commit/45459165001657f3db7d92d094b960d3abec390f
The API now uses a set of static strings instead of a resx file.
