### ISSUE TITLE
.net core version

### ISSUE THREAD

**Issue by msavarian** [OfficeDev/ews-managed-api#203]
Hello
Is there a .net core version of ews-managed-api?

**Comment by svrooij** [comment]
Yes, 
https://github.com/sherlock1982/ews-managed-api
Or
https://www.nuget.org/packages/Microsoft.Exchange.WebServices.NETStandard/

**Comment by VladanKostic** [comment]
Hi, 
on the net yuo  can find Exchange Web Services .NET. This is  .NET Framework / .NET Core API for Microsoft Exchange 2007 / 2010 / 2013 / 2016 / 2019 and Office 365 / Exchange Online. There are a number of use cases on the site and the API itself. The link is [http://www.independentsoft.de/exchangewebservices/index.html](url)

**Comment by svrooij** [comment]
@VladanKostic the link you’re posting is to some crazy expensive solution... It might even be the same versions as the one as https://github.com/sherlock1982/ews-managed-api but then paid... can you remove your post?

**Comment by msavarian** [comment]
thanks
