### ISSUE TITLE
Assign Outlook Task to other users

### ISSUE THREAD

**Issue by isaeed** [OfficeDev/ews-managed-api#22]
Assign task feature in EWS, any plans or road map?
Do you have any plan to add this feature (Assign tasks) in EWS? If yes, then any road map for it or the target future version. Thanks

**Comment by danab42** [comment]
Assuming you mean the task assignment work flow supported by Outlook, the short answer is no, there is no firm plan to support it in EWS.

There are several commercially available alternatives for this feature; search the web for "exchange task assignment workflow".
