### ISSUE TITLE
Load EmailMessage from eml file and read properties value

### ISSUE THREAD

**Issue by rk1984** [OfficeDev/ews-managed-api#23]
I'm fetching and saving emails from Exchange to file system as eml files.
I'm able to read the eml files, but cannot read emailmessage properties value, because first I need to load the message. When I try to load the message I get this error:
This operation can't be performed because this service object doesn't have an Id

Can anyone help me dealing with this?

Thank you!

**Comment by dclaux** [comment]
Hi there, could you share your code? I am not 100% sure what you're trying to do.

**Comment by rk1984** [comment]
I'm able to save emailmessage as .eml in local disk.

Now, here is the code I used to get the eml emailmessage from disk:
var email = new EmailMessage(_exchangeService);

            string emlFileName = fileName;

            using (var fs = new FileStream(emlFileName, FileMode.Open, FileAccess.Read))
            {
                var bytes = new byte[fs.Length];
                int numBytesToRead = (int)fs.Length;
                int numBytesRead = 0;

                while (numBytesToRead > 0)
                {
                    int n = fs.Read(bytes, numBytesRead, numBytesToRead);

                    if (n == 0)
                        break;

                    numBytesRead += n;
                    numBytesToRead -= n;
                }

                // Set the contents of the .eml file to the MimeContent property.
                email.MimeContent = new MimeContent("UTF-8", bytes);
            }

//Here it throws an exception with message This operation can't be performed because this service object doesn't have an Id
email.Load();

var from =  email.From
var to = emai.ToRecipients
...

I need to be able to get values of email properties like From, ToRecipients, Cc, Bcc, EmailBody etc.

**Comment by dclaux** [comment]
You can only set the MimeContent property to create an item, so in your case email.MimeContent = <your mime> would have to be followed by email.Save() to create the email in Exchange. You will then have to Load the email to retrieve the values of the extracted properties.

**Comment by rk1984** [comment]
In my case, I'm fetching emails from Exchange and saving them locally in order to push them to an IMAP server.
Currently, my only issue is how to load the email from disk and be able to access email properties values. Any help from your side, will make my life easier :)
Thanks!

**Comment by dclaux** [comment]
The EWS Managed API does not provide a built-in way to parse MIME, so your only options are either to "stage" an email on the server (e.g. to actually create it with your MIME so the server does the parsing) or to use a third party library. There seems to be a few available out there, including on CodePlex.
