### ISSUE TITLE
Cannot create a calendar item in a non-calendar folder

### ISSUE THREAD

**Issue by rk1984** [OfficeDev/ews-managed-api#25]
I'm getting this error when trying to push contacts and tasks to Exchange.
Here is the content of one of the contact:
BEGIN:VCARD
PROFILE:VCARD
VERSION:3.0
MAILER:Microsoft Exchange
PRODID:Microsoft Exchange
FN:First  M. Person
N:Person;First ;M.;;
ORG:;
CLASS:PUBLIC
ADR;TYPE=WORK:;;;;;;
LABEL;TYPE=WORK:
ADR;TYPE=HOME:;;;;;;
LABEL;TYPE=HOME:
ADR;TYPE=POSTAL:;;;;;;
LABEL;TYPE=POSTAL:
TEL;TYPE=WORK:
TEL;TYPE=WORK:
TEL;TYPE=HOME:
TEL;TYPE=HOME:
TEL;TYPE=CELL:
TEL;TYPE=PAGER:
TEL;TYPE=CAR:
TEL;TYPE=ISDN:
TEL;TYPE=PREF:
TEL;TYPE=VOICE:
X-MS-TEL;TYPE=ASSISTANT:
X-MS-TEL;TYPE=TTYTDD:
X-MS-TEL;TYPE=CALLBACK:
X-MS-TEL;TYPE=RADIO:
X-MS-TEL;TYPE=COMPANY:
X-MS-MANAGER;TYPE=N:
X-MS-ASSISTANT;TYPE=N:
EMAIL;TYPE=TLX:
TITLE:
X-MS-IMADDRESS:
URL;TYPE=WORK:
REV;VALUE=DATE-TIME:2015-03-17T15:00:09,506Z
END:VCARD

**Comment by LukeMarlin** [comment]
Given the error and what you say you are trying to achieve, you are probably doing something wrong.
Can you show the code you use ?

**Comment by rk1984** [comment]
Hi Luke,

Thanks for quick response!

Here the code:

**Comment by dclaux** [comment]
Can you post the code that sets up the items collection? Do you set the MimeContent property of those items?

**Comment by rk1984** [comment]
Here I'll explain all the procedure.
I'm fetching data from one Exchange server, saves them locally. Below is the code I use to fetch and save items locally:
                Folder rootFolder = Folder.Bind(_exchangeService, WellKnownFolderName.MsgFolderRoot);

for each folder under root folder, I do this loop
 foreach (var item in folder.FindItems(new ItemView(int.MaxValue)))
            {
                try
                {
                    var props = new PropertySet(ItemSchema.MimeContent);
                    var bindItem = Item.Bind(_exchangeService, item.Id, props);
...
                    if (!File.Exists(emlFileName))
                        using (var fs = new FileStream(itemFileName, FileMode.Create, FileAccess.Write))
                            fs.Write(bindItem.MimeContent.Content, 0, bindItem.MimeContent.Content.Length);

                }
                catch (Exception ex)
                {
                    ...
                }
            }

After that, I go through all saved items, load them and try to push to destination Exchange server:

//load item from file
Item item;
switch (folderType)
            {
                case FolderType.Calendar:
                    item = new Appointment(_exchangeService);
                    break;
                case FolderType.Contacts:
                    item = new Contact(_exchangeService);
                    break;
                case FolderType.Email:
                    item = new EmailMessage(_exchangeService);
                    break;
                case FolderType.Tasks:
                    item = new Task(_exchangeService);
                    break;
            }

using (var fs = new FileStream(itemFileName, FileMode.Open, FileAccess.Read))
            {
                var bytes = new byte[fs.Length];
                int numBytesToRead = (int)fs.Length;
                int numBytesRead = 0;

                while (numBytesToRead > 0)
                {
                    int n = fs.Read(bytes, numBytesRead, numBytesToRead);

                    if (n == 0)
                        break;

                    numBytesRead += n;
                    numBytesToRead -= n;
                }

                // Set the contents of the file to the MimeContent property.
                item.MimeContent = new MimeContent("UTF-8", bytes);
            }

            var prMessageFlagsMsgflagRead = new ExtendedPropertyDefinition(3591, MapiPropertyType.Integer);
            item.SetExtendedProperty(prMessageFlagsMsgflagRead, 1);

....
//add item to list of items
items.Add(item);

...

//push items to destination server
var exchangeFolder = GetExchangeFolder(folder);
ServiceResponseCollection serviceResponse;
if (exchangeFolder != null)
serviceResponse = _exchangeService.CreateItems(items, exchangeFolder.Id,
MessageDisposition.SaveOnly, SendInvitationsMode.SendToNone);


Code are not in the same place, I hope it's clear to have an idea how I save, load and push items.

Thank you for your time!

**Comment by dclaux** [comment]
If you're going to create the items using MimeContent, just create Item instances instead of EmailMessage, Appointment etc. I think that should do the trick.

**Comment by LukeMarlin** [comment]
Just a warning about this :

    folder.FindItems(new ItemView(int.MaxValue))

The default configuration of Exchange will only return 1000 items. So it's fine if you changed the limit, but if you have the default value you will be missing items.

**Comment by rk1984** [comment]
You mean FindItems default configuration returns only 1000 items?

I'm still having problem saving contacts and tasks and pushing them to destination server. Here is the error message I get when trying to push Contacts and Tasks, other items just work fine:
MIME conversion is not supported for this item type

**Comment by LukeMarlin** [comment]
No, `FindItems` doesn't have a "configuration". I mean that when using this, you are asking the server to return `Int32.MaxValue` items, but the server will returns only what is allowed by his configuration. Out of the box, it is (As far as I know), 1000 items.

**Comment by rk1984** [comment]
That's weird! How can I iterate through all items then!?

Any idea how can I save and load Contacts and Tasks. As I mentioned above, I used this code to save items (including tasks and contacts):
<pre>
foreach (var item in folder.FindItems(new ItemView(int.MaxValue)))
{
try
{
var props = new PropertySet(ItemSchema.MimeContent);
var bindItem = Item.Bind(_exchangeService, item.Id, props);
...
if (!File.Exists(emlFileName))
using (var fs = new FileStream(itemFileName, FileMode.Create, FileAccess.Write))
fs.Write(bindItem.MimeContent.Content, 0, bindItem.MimeContent.Content.Length);
...
</pre>

I'm able to save all items, but when trying to push using code below, it fails to push only contacts and tasks and give me this error "MIME conversion is not supported for this item type".
<pre>_service.CreatItems(items, exchangeFolder.Id,
MessageDisposition.SaveOnly, SendInvitationsMode.SendToNone);</pre>

Any help would be great!

Thanks again!

**Comment by LukeMarlin** [comment]
I'd say that the error means that you won't be able to do it via MimeContent, and that you won't be able to do something about it. However I'm not used to MimeContent so you better wait for another answer from @dclaux...

Regarding the items iteration, here is a sample code (that probably can be refactored) :

    var foundItems = _service.FindItems(folder, filters, view);
    items.AddRange (foundItems);
    while (foundItems.MoreAvailable && foundItems.NextPageOffset != null)
    {
        view.Offset = foundItems.NextPageOffset.Value;
        foundItems = _service.FindItems(folder, filters, view);
        items.AddRange(foundItems);
    }
    
I'd need to try this out again, but I'm pretty sure that without filters on receive/create date, if a new element is created during you iteration, you will experience duplicates items so you might want to add a filter with current timestamp.

**Comment by dclaux** [comment]
@rk1984 in your code:
```
_service.CreatItems(items, exchangeFolder.Id,
MessageDisposition.SaveOnly, SendInvitationsMode.SendToNone);
```
What does the items collection contain? Instances of Item, or instances of EmailMessage, Contact, Task, etc.?

**Comment by dclaux** [comment]
Creating Contact and Task items via MimeContent is not supported by EWS. For those item types you will have to resort to a different approach.

**Comment by rk1984** [comment]
@dclaux instance of items are created dynamically, based on folders. I'm done with it now.

As per contact and task, I'm trying to fetch and push without saving in file system, because I cannot load them then.
Here is a piece of my code (same applies for task):
<pre>
            foreach (var contact in contacts)
            {
                var contactToPush = new Contact(_exchangeService);
//here I do manual mapping; no chance to get working with AutoMapper :'(
//I'm passing ExchangeVersion, because I need to check properties availability 
                ContactMapper.MapContact(contact, contactToPush, _exchangeService.RequestedServerVersion);
                contactToPush.Save(WellKnownFolderName.Contacts);
            }
<pre>

**Comment by dclaux** [comment]
That sounds like a valid approach for Task and Contact.
Is it OK to close this issue at this point?

**Comment by rk1984** [comment]
Yes, you can close it.

Thank you!
