### ISSUE TITLE
In certain configs Unauthorized HTTP response for AutoDiscover query is eaten up and surfaced as AutodiscoverLocalException

### ISSUE THREAD

**Issue by stefann42** [OfficeDev/ews-managed-api#26]
Our app, www.FreeBusy.io acts as an Exchange client and uses EWS AutoDiscover. We have users with on-premise Exchange Servers and their AutoDiscover setup exposes a single endpoint at "autodiscover.contoso.com" on port 443. They don't have port 80 open and they don't have an SRV record in DNS.

Unfortunately, for this particular configuration EWS Managed Library treats Unauthorized as if AutoDiscover service wasn't even configured. When a user incorrectly types their password Fiddler traces show two requests:
1) GET https://autodiscover.contoso.com/autodiscover/autodiscover.xml on port 443 (returns HTTP 401)
2) GET http://autodiscover.contoso.com/autodiscover/autodiscover.xml on port 80 (fails because port 80 isn't open).

EWS Managed Library considers HTTP 401 response the same as if the request to the HTTPS endpoint completely failed which is certainly not the case. Because library throws AutodiscoverLocalException we can't distinguish between this scenario and a client who's AutoDiscover service isn't configured at all. We can't tell the user that they just typed the wrong password and we end up asking them for detailed EWS configuration when we could have obtained the data from the AutoDiscover service.

Expected behavior: library should throw a ServiceRequestException from which we can extract the HTTP status code and understand that the service is available, just the wrong password was supplied.

**Comment by dclaux** [comment]
Hi there,
Have you set the Credentials property of the ExchangeService instance you call AutodiscoverUrl on? The API should definitely not consider a 401 as a failure unless it actually can't authenticate.

**Comment by stefann42** [comment]
Yes. The same code gives expected result for users who are Office 365 tenants. But Office 365 has AutoDiscover configured differently from what I described above. The sequence for Office 365 tenants is:
1) GET https://autodiscover.contoso.com/autodiscover/autodiscover.xml on port 443 (fails because port 443 isn't open)
2) GET http://autodiscover.contoso.com/autodiscover/autodiscover.xml on port 80 (returns HTTP 302 response with a redirect location of https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml)
3) GET https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml on port 443 (returns HTTP 401)
4) POST https://autodiscover-s.outlook.com/autodiscover/autodiscover.svc on port 443 (returns HTTP 401)

In this case library correctly throws ServiceRequestException. So the bug is very specific to the AutoDiscover config I described in the main bug report.

**Comment by dclaux** [comment]
So, if my memory serves correctly:
- The first GET is supposed done just to get a feel of the Autodiscover service version. It's always an unauthenticated request because the info the API needs is returned in HTTP headers
- If the API determines that Autodiscover is available at that URL, it sends a POST to it to get the settings
- Otherwise, it follows the next steps in the Autodiscover process (described here: https://msdn.microsoft.com/en-us/library/office/ee332364(v=exchg.140).aspx)

So in this case, it looks like https://autodiscover.contoso.com/autodiscover/autodiscover.xml does not return headers that make it look like an Autodiscover endpoint. A trace would be helpful.

**Comment by stefann42** [comment]
Indeed, there's no AutoDiscover specific header. FWIW user says their IT dept is running [Forefront TMG](https://technet.microsoft.com/en-us/library/ff355324.aspx) in front of their OWA server. I wonder if TMG isn't rewriting the 401 response because this is what comes back:
```
HTTP/1.1 401 Unauthorized ( The server requires authorization to fulfill the request. Access to the Web server is denied. Contact the server administrator.  )
WWW-Authenticate: Negotiate
WWW-Authenticate: Kerberos
WWW-Authenticate: NTLM
WWW-Authenticate: Basic realm="autodiscover.contoso.com"
Connection: Keep-Alive
Pragma: no-cache
Cache-Control: no-cache
Content-Type: text/html
Content-Length: 2073
Proxy-Support: Session-Based-Authentication

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML dir=ltr><HEAD><TITLE>The page cannot be displayed</TITLE>
<STYLE id=L_defaultr_1>A:link {
	FONT: 8pt/11pt verdana; COLOR: #ff0000
}
A:visited {
	FONT: 8pt/11pt verdana; COLOR: #4e4e4e
}
</STYLE>
<META content=NOINDEX name=ROBOTS>
<META http-equiv=Content-Type content="text-html; charset=UTF-8">
<META content="MSHTML 5.50.4522.1800" name=GENERATOR></HEAD>
<BODY bgColor=#ffffff>
<TABLE cellSpacing=5 cellPadding=3 width=410>
  <TBODY>
  <TR>
    <TD id=L_defaultr_0 valign=middle align=left width=360>
      <H1 id=L_defaultr_2 style="FONT: 13pt/15pt verdana; COLOR: #000000"><ID id=L_defaultr_3><!--Problem-->The page cannot be displayed
</ID></H1></TD></TR>
  <TR>
    <TD width=400 colSpan=2><FONT id=L_defaultr_4
      style="FONT: 8pt/11pt verdana; COLOR: #000000"><ID id=L_defaultr_5><B>Explanation: </B>There is a problem with the page you are trying to reach and it cannot be displayed.</ID></FONT></TD></TR>
  <TR>
    <TD width=400 colSpan=2><FONT id=L_defaultr_6 
      style="FONT: 8pt/11pt verdana; COLOR: #000000">
      <HR color=#c0c0c0 noShade>
      <P id=L_defaultr_7><B>Try the following:</B></P>
      <UL>
        <LI id=L_defaultr_8><B>Refresh page:</B> Search for the page again by clicking the Refresh button. The timeout may have occurred due to Internet congestion.
<LI id=L_defaultr_9><B>Check spelling:</B> Check that you typed the Web page address correctly. The address may have been mistyped.
<LI id=L_defaultr_10><B>Access from a link:</B> If there is a link to the page you are looking for, try accessing the page from that link.
      </UL>
      <HR color=#c0c0c0 noShade>
      <P id=L_defaultr_11>Technical Information (for support personnel)</P>
      <UL>
        <LI id=L_defaultr_12>Error Code: 401 Unauthorized. The server requires authorization to fulfill the request. Access to the Web server is denied. Contact the server administrator. (12209)
        </UL></FONT></TD></TR></TBODY></TABLE></BODY></HTML>
```

**Comment by stefann42** [comment]
According to this Microsoft whitepaper [Publishing Exchange Server 2010 with Forefront Unified Access Gateway 2010 and Forefront Threat Management Gateway 2010](http://www.microsoft.com/en-us/download/details.aspx?id=8946) there are several ways in which you can shoot yourself in the foot by only exposing the OWA URL for humans (with forms auth) and not the EWS URL for programmatic access.

So I'll close this ticket for now, at least until I can confirm with the user their TMG is correctly exposing EWS. Thanks for jumping in!

**Comment by dclaux** [comment]
Thanks for the update.
