### ISSUE TITLE
Recurrence.YearlyRegenerationPattern and Recurrence.YearlyPattern should be an Recurrence.IntervalPattern

### ISSUE THREAD

**Issue by tempel3** [OfficeDev/ews-managed-api#27]
In Outlook 2013 an yearly appointment with an interval can be created.

Unfurnately Recurrence.YearlyPattern does not provide an corresponding attribute.

I assume, this is a new exchange feature and YearlyPattern was not changed yet.

**Comment by dclaux** [comment]
Unfortunately the service itself doesn't support interval yearly patterns, so changing this in the API isn't enough.

**Comment by MarkEdward-BarS** [comment]
I've just been setting up recurrence patterns in our system that syncs with EWS, and come up against this bug. The YearlyRegenerationPattern has the interval property required, and Outlook can create these appointments OK.

Have subsequent versions of EWS fixed this? Although I'm syncing with an Office 365 account, and experiencing the problem, so I guess not.

Any info would be appreciated, if only out of interest, thanks.
