### ISSUE TITLE
Conversation object throws instead of returning null

### ISSUE THREAD

**Issue by konste** [OfficeDev/ews-managed-api#33]
Class Conversation, derived from ServiceObject has GetExtendedProperties() override implemented as throw new NotSupportedException();

At the same time ServiceObject.GetLoadedPropertyDefinitions() expects GetExtendedProperties to return null if it is not implemented, otherwise Conversation.GetLoadedPropertyDefinitions() can never return anything - it always throws! Please fix.

Thank you!
Konstantin

**Comment by dclaux** [comment]
Hi @konste Thanks for reporting this, GetExtendedProperties shouldn't be overridden in Conversation (the base class returns null.) That said, this really is a problem only if you're handling a collection of ServiceObject instances in a generic way, and calling GetLoadedPropertyDefinitions. Is that what you do?

**Comment by konste** [comment]
Yes, exactly! I'm refactoring older code which tries to clone Exchange object by requesting its properties one by one and blowing on each one which is not loaded. GetLoadedPropertyDefinitions solves this problem nicely - I can iterate over it and call TryGetProperty on each returned ServiceObject, but for Conversations I have to put a workaround in place. 

Too bad we don't have something like that for ComplexProperty objects. It would be great to read their properties in generic and unified way too.

**Comment by dclaux** [comment]
Fixed: https://github.com/OfficeDev/ews-managed-api/commit/1aac1452942a0742b48fe385207216aae788887f
