### ISSUE TITLE
FindPeople isn't supported

### ISSUE THREAD

**Issue by SaqibS** [OfficeDev/ews-managed-api#38]
I have an application which is using this API, but I now need to use the FindPeople operation. This is exposed via the SOAP service, but not via the managed API. Please could you add this?
I can help with the implementation, but will likely have questions whilst ramping up on the codebase.

**Comment by dclaux** [comment]
FindPeople was recently added to the the API with this change:https://github.com/OfficeDev/ews-managed-api/commit/45459165001657f3db7d92d094b960d3abec390f
Please use the latest code base, and you should be all set.
