### ISSUE TITLE
Is there any way to activate the latent JSON mode?

### ISSUE THREAD

**Issue by ciddan** [OfficeDev/ews-managed-api#41]
Reading the code it seems like it should be possible to use JSON objects instead of XML for data transport. I can't find a way to make that happen, though. Is it not done yet? Am I missing something?

**Comment by dclaux** [comment]
Your question comes at an interesting time... I'm working on removing JSON support from the API. There is no way to actually use JSON for data transport. JSON support was added originally for internal testing purposes, but it's not used anymore.
