### ISSUE TITLE
AutoDiscoverService always uses old reponse format 

### ISSUE THREAD

**Issue by gdezz** [OfficeDev/ews-managed-api#43]
Hi,

I needed to get MAPI over HTTP Uri and doing so i found that the method InternalGetLegacyUserSettings is invoked only if requested server version is less than Exchange2010.

It seems that it should be the opposite.

Regards,
Dezz

**Comment by dclaux** [comment]
A new SOAP-based version of Autodiscover was introduced in Exchange2010, and the API makes use of it instead of the older version whenever possible. This is by design.

**Comment by serious6** [comment]
:+1:

**Comment by gdezz** [comment]
Thanks for the quick answer,
You're right, I have now found that the reference document in Exchange Protocols is MS-OXWSADISC for this  API.

Regards,
