### ISSUE TITLE
Suggestion: return FolderID for Folder.Save()

### ISSUE THREAD

**Issue by aribeth97** [OfficeDev/ews-managed-api#50]
EWS CreateFolder returns FolderID of newly created folder, but Managed API Folder.Save() does not.

Returning FolderID is useful in many cases, such as creating folder hierarchy. The workaround is to use Find after creation which seems....inconvenient.

**Comment by dclaux** [comment]
Hi, after folder.Save() has succeeded, folder.Id contains the Id of the newly created folder.
