### ISSUE TITLE
EWS Java API for User Availability not working for FreeBusyandSuggestions

### ISSUE THREAD

**Issue by ramamurari** [OfficeDev/ews-managed-api#53]
Hi,

We are using the EWS Java API to get calendar services of Office 365.
In GetUserAvailability , when the requested data is  "FreeBusy" or "Suggestions", it works fine.
But, it does not work for "FreeBusyAndSuggestions" . It gives the following error ",  “The request failed. An internal server error occurred. The operation failed.” We are using EWS snapshot version 2.0. Can you please help us here

Thanks and Regards.
Rama.

**Comment by dclaux** [comment]
This forum is for the EWS Managed API. For EWS Java API questions please post in the [ews-java-api] (https://github.com/OfficeDev/ews-java-api) project.
