### ISSUE TITLE
MissingManifestResourceException

### ISSUE THREAD

**Issue by teharris1** [OfficeDev/ews-managed-api#7]
The exception is thrown in ExchangeResourceManager.GetString(string name, System.Globalization.CultureInfo culture) when calling Autodiscovery. The resource string is "NoError" but I believe this exception would occur with any resource.

**Comment by joseph-ortiz** [comment]
When adding the resources.resx file correctly, can you clarify by what you mean by "correctly"? I'm still getting errors. Error	1	

The type or namespace name 'Properties' does not exist in the namespace 'Microsoft.Exchange.WebServices.Data' (are you missing an assembly reference?)	C:\Users\jortiz\ews-managed-api\Microsoft.Exchange.WebServices.Strings.cs	2366	212	Microsoft.Exchange.WebServices.Data

This is what I did.

1)  I created a Resources.resx file and pasted the example above.
2)  I placed the Resources.resx file in the Properties folder and included it to the project.
3) I then referenced the same Manifest file in the Application Tab --> Resources --> Resource file

**Comment by martinguenther** [comment]
I can't recall what exactly I did to make it work. Sorry. I remember starting from the beginning. Then it worked. As I wrote back then, it was not clear to me what exactly the error on my first approach was.

**Comment by dclaux** [comment]
Hi there, an updated code base is coming shortly that removes the need for a resx file.
