### ISSUE TITLE
StreamingSubscriptionConnection.IsOpen incorrectly reporting status

### ISSUE THREAD

**Issue by rojobo** [OfficeDev/ews-managed-api#83]
This is a reproduction of https://github.com/OfficeDev/ews-managed-api/issues/8

I'm doing some tests and when the Connection disconnects (due to reaching the lifetime limit) I re-open the connection but after that the IsOpen method returns false everytime even though I'm able to receive notifications through the subscription and the connection keeps disconnecting (when reaching the lifetime limit).

The only difference from https://github.com/OfficeDev/ews-managed-api/issues/8

(I've tested reopening as high as 70 StreamingSubscriptionConnections  in this case)  

I started out testing with 2 StreamingSubscriptionConnections, thats when I first noticed the symptoms, then I proceeded to do a google search and found that a couple of people have had the same experience but on all instances they have marked the issue as being fixed in a previous release (https://github.com/OfficeDev/ews-managed-api/issues/8). However that's not the case at least for me, when the OnDisconnect event fires I do a connection.Open() , then I look at the object via the Visual Studio Watch and the isOpen property is False.

Before:

![image](https://cloud.githubusercontent.com/assets/8916554/14179553/1ce41c3e-f725-11e5-9a13-a3cafcce91dc.png)

![image](https://cloud.githubusercontent.com/assets/8916554/14179577/37e55250-f725-11e5-9495-610f9cc64a09.png)

After OnDisconnect Events:

![image](https://cloud.githubusercontent.com/assets/8916554/14179637/6dd4b946-f725-11e5-805f-336ff150f7e6.png)

I change something in the mailbox to see if I'm still able to get the notifications and it turns out that I still do!

I decide to do some more testing and after calling connection.Open() I do a check to see if the IsOpen property is false 

![image](https://cloud.githubusercontent.com/assets/8916554/14178914/86f1be0e-f722-11e5-8ae8-d4ba0218fcbe.png)

if it is I try calling connection.open() once again and I get this error.

![image](https://cloud.githubusercontent.com/assets/8916554/14179239/071ff72a-f724-11e5-82a8-171e72096ab7.png)

@vboctor @dclaux

**Comment by rojobo** [comment]
UPDATE: It was brought to my attention that Microsoft has not updated the Nuget Package so this may have already be addressed in the previous release.

**Comment by ethan-deng** [comment]
When calling "open" on the connection without checking IsOpen, sometime it will throw this error.

The connection has already opened.   at Microsoft.Exchange.WebServices.Data.StreamingSubscriptionConnection.ValidateConnectionState(Boolean isConnectedExpected, String errorMessage) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Notifications\StreamingSubscriptionConnection.cs:line 287
   at Microsoft.Exchange.WebServices.Data.StreamingSubscriptionConnection.Open() in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Notifications\StreamingSubscriptionConnection.cs:line 198

However if do check "IsOpen" and it returns true after disconnected what to do?
